config/routes.rb
Gotrucker::Application.routes.draw do
  devise_for :users, :controllers => { registrations:  'users/registrations',
                                      :sessions => "users/sessions",
                                      :passwords => 'users/passwords',
                                      :confirmations => 'users/confirmations'
  }
  authenticate :user do
    namespace :users do
      resources :ui
      resources :users
      resources :accounts, :only => [:show, :edit, :update]
      resources :drivers
      resources :profile, :only => [:edit, :update]
      resources :trucks
      resources :trailers
      resources :brokers do
        collection { post :import }
      end
      match "/shipments/delete" => "shipments#delete", :as => :shipments_delete
      resources :shipments
      resources :receipts
      resources :repairs
      match '/invoices/:id/pdf' => 'invoices#pdf', :as => :invoices_pdf
      resources :invoices
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

   devise_for :admins, :controllers => { registrations: 'admins/registrations',
                                       :sessions => "admins/sessions",
                                       :passwords => 'admins/passwords',
                                       :confirmations => 'admins/confirmations'
   }
   authenticate :admin do
     namespace :admins do
       resources :ui
       resources :accounts
       resources :admins
       resources :brokers
       resources :drivers
       resources :leads
       resources :plans
       resources :profile, :only => [:edit, :update]
       resources :receipts
       resources :repairs
       resources :shipments
       resources :trailers
       resources :trucks
       resources :users
       post '/users/login_as' => 'users#login_as', as: :login_as_user
       get '/dashboard' => 'dashboards#index', as: :dashboard
       get '/' => 'dashboards#index'
     end
   end

#   namespace :api do
#     namespace :internal do
#       namespace :v1 do
#         resources :users
#         resources :drivers
#         resources :trucks
#         resources :trailers
#         resources :brokers
#         resources :shipments
#         resources :receipts
#         resources :repairs
#         resources :invoices
#       end
#     end
#   end
  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us
  match '/thanks' => 'leads#thanks', :as => :thanks
  match "/prices" => "pages#prices", :as => :prices
  match "/about_us" => "pages#about_us", :as => :about_us
  match "/test" => "pages#test", :as => :test
  root :to => 'pages#index'
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
  has_one :truck
  has_many :shipments
  belongs_to :account
  has_many :comments, :as => :commenter

  attr_accessible :name, :length, :width, :height, :gross_vehicle_weight_rating, :suspension, :axle_capacity, :wheels, :tires, :trailer_type, :photo, :account_id, :vehicle_identification_number, :vehicle_tag, :annual_inspection, :vented, :year_build, :manufacturer, :annual_inspection_pdf, :insurance_pdf, :registration_pdf
  
  validates_uniqueness_of :name, :scope => :account_id
  mount_uploader :photo, PhotoUploader
  mount_uploader :annual_inspection_pdf, FileUploader
  mount_uploader :insurance_pdf, FileUploader
  mount_uploader :registration_pdf, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  has_many :comments
  has_many :comments, :as => :commenter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :photo, :phone, :active, :is_owner, :is_primary, :account_id, :plan_slug, :s, :account_attributes, :subscriptions_type

  validates_uniqueness_of :email
  validates_presence_of :password, :if => :should_validate_password?

  attr_accessor :updating_password
  attr_accessor :plan_slug
  attr_accessor :s
  attr_accessor :subscriptions_type
  accepts_nested_attributes_for :account
  mount_uploader :photo, PhotoUploader

  def name
    full_name
  end

  def full_name
    first_name + ' ' + last_name
  end
  def should_validate_password?
      updating_password || new_record?
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminController
  before_filter :check_password_submitted, :only => :update
  expose(:users) {User.order("id DESC").scoped{}}
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(admins_user_path(user))
    else
      render :new
    end
  end

  def update
    if user.update_attributes(params[:user])
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(admins_user_path(user))
    else
      render :edit
    end
  end
  def login_as
    sign_in(User.find(params[:id]), :bypass => true)
    redirect_to users_dashboard_path
  end
  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/api/internal/v1/users_controller.rb
class Api::Internal::V1::UsersController < ApiController
  expose(:users){ User.all }
  expose(:user){ User.find(params[:id]) }
  respond_to :json
  before_filter :check_api_key


  private
  def check_api_key
    unless params['api_key'] == ENV['INTERNAL_API_KEY']
      respond_with({:result => 'Invalid API Key'})
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  expose(:current_account){ current_user.account }
  layout 'user_application'
  before_filter :check_user_active
  before_filter :check_unpaid_invoices
  private
    def check_user_active
      unless current_user.active
        flash[:notice]= t(:user_not_active)
        sign_out current_user
        redirect_to new_user_session_path
      end
    end
    def check_unpaid_invoices
      if current_account.invoices.count > 0
        if current_account.invoices.where(:paid_status => 'unpaid').where("created_at <= ?", Time.now - 30.days).count > 0
          flash[:error]= 'There are unpaid invoices over 30 days'
        end
      end
  end
end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < UserController
  before_filter :check_user_level
  expose(:account) {current_account}

  def create
    if account.save
      flash[:notice] = t(:account_was_successfully_created)
      redirect_to(users_account_path(current_account))
    else
      render :new
    end
  end

  def update
    if account.update_attributes(params[:account])
      flash[:notice] = t(:account_was_successfully_updated)
      redirect_to(users_account_path(current_account))
    else
      render :edit
    end
  end
  private
  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/controllers/users/brokers_controller.rb
class Users::BrokersController < UserController
  require 'csv'
  expose(:brokers){ current_account.brokers.order("id DESC").scoped{} }
  expose(:broker)
  expose(:comment) { broker.comments.new}

  def create
    if broker.save
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
    else
      render :new
    end
  end

  def update
    if broker.save
      flash[:notice] = t(:broker_was_successfully_updated)
      redirect_to(users_brokers_path)
    else
      render :edit
    end
  end


  def import
    puts params
    csv_text = File.read('public/brokers.csv')
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
        current_account.brokers.create!(row.to_hash)
    end
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
  end 
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:drivers){ current_account.drivers.where(:active => true).order("id DESC").scoped{} }
end

app/controllers/users/drivers_controller.rb
class Users::DriversController < UserController
  expose(:drivers){ current_account.drivers.order("id DESC").scoped{} }
  expose(:driver)
  expose(:comment) { driver.comments.new}

  def create
    if driver.save
      flash[:notice] = t(:driver_was_successfully_created)
      redirect_to(users_drivers_path)
    else
      render :new
    end
  end

  def update
    if driver.save
      flash[:notice] = t(:driver_was_successfully_updated)
      redirect_to(users_drivers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/invoices_controller.rb
class Users::InvoicesController < UserController
  expose(:invoices){ current_account.invoices.order("id DESC").scoped{} }
  expose(:invoice)
  expose(:comment) { invoice.comments.new}
  expose(:shipment) {
    if params[:shipment]
      current_account.shipments.find(params[:shipment])
    else
      false
    end
  }

  def create
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_created)
      redirect_to(users_invoices_path)
    else
      render :new
    end
  end

  def update
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_updated)
      redirect_to(users_invoices_path)
    else
      render :edit
    end
  end
  
  def pdf
    render :layout => 'invoice'
    #render :layout => false  
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'user_login'
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < UserController
  before_filter :check_password_submitted, :only => :update
  expose(:user){ current_user }
  def update
    if user.update_attributes(params[:user])
      sign_in(current_user, :bypass => true)
      flash[:notice] = t(:profile_was_successfully_updated)
      redirect_to users_dashboard_path
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/users/receipts_controller.rb
class Users::ReceiptsController < UserController
  expose(:receipts){ current_account.receipts.order("id DESC").scoped{} }
  expose(:receipt)
  expose(:comment) { receipt.comments.new}

  def create
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_created)
      redirect_to(users_receipts_path)
    else
      render :new
    end
  end

  def update
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_updated)
      redirect_to(users_receipts_path)
    else
      render :edit
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 #layout 'application'
 before_filter :before_create_account, :only => [:create]
 after_filter :account_must_have_a_plan, :only => [:create]
 expose(:plan){Plan.find_by_slug(params[:plan])}
 def new
  redirect_to user_dashboard_path if current_user
  resource = build_resource({})
  resource.build_account
  resource.account.build_subscription
  resource.plan_slug = plan.slug if plan
  respond_with resource
 end

 def after_inactive_sign_up_path_for(resource)
   users_dashboard_path
 end

 def after_sign_up_path_for(resource)
   sign_in(resource)
   users_dashboard_path
 end

 private
 def before_create_account
    params[:user][:is_owner] = true
    params[:user][:is_primary] = true
 end

 def account_must_have_a_plan
   unless resource.new_record?
     s = Subscription.find_by_key(params[:user][:s])
     plan = Plan.find_by_slug(s.item_number)

     params[:user][:subscriptions_type] = 'monthly'
     if params[:user][:subscriptions_type] == 'monthly'
       price = plan.monthy_price
     else
       price = plan.yearly_price
     end
     s.update_attributes(:account_id => resource.account.id, :plan_id => plan.id, :name => plan.name, :price => price, :slug => plan.slug, :licenses => plan.licenses, :subscriptions_type => params[:user][:subscriptions_type]  )
   end
 end

end

app/controllers/users/repairs_controller.rb
class Users::RepairsController < UserController
  expose(:repairs){ current_account.repairs.order("id DESC").scoped{} }
  expose(:repair)
  expose(:comment) { repair.comments.new}

  def create
    if repair.save
      flash[:notice] = t(:repair_was_successfully_created)
      redirect_to(users_repairs_path)
    else
      render :new
    end
  end

  def update
    if repair.save
      flash[:notice] = t(:repair_was_successfully_updated)
      redirect_to(users_repairs_path)
    else
      render :edit
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'user_login'
  private
  def after_sign_in_path_for(resource)
    users_dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/users/shipments_controller.rb
class Users::ShipmentsController < UserController
  expose(:shipments){ current_account.shipments.order("id DESC").scoped{} }
  expose(:shipment)
  expose(:comment) { shipment.comments.new}

  def create
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_created)
      redirect_to(users_shipments_path)
    else
      render :new
    end
  end

  def update
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_updated)
      redirect_to(users_shipments_path)
    else
      render :edit
    end
  end
   def delete
     s = Shipment.find(params[:format])
     s.delete
      flash[:notice] = t(:shipment_was_successfully_deleted)
      redirect_to(users_shipments_path)
   end
end

app/controllers/users/trailers_controller.rb
class Users::TrailersController < UserController
  expose(:trailers){ current_account.trailers.order("id DESC").scoped{} }
  expose(:trailer)
  expose(:comment) { trailer.comments.new}

  def create
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_created)
      redirect_to(users_trailers_path)
    else
      render :new
    end
  end

  def update
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_updated)
      redirect_to(users_trailers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/trucks_controller.rb
class Users::TrucksController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:truck)
  expose(:comment) { truck.comments.new}

  def create
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_created)
      redirect_to(users_trucks_path)
    else
      render :new
    end
  end

  def update
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_updated)
      redirect_to(users_trucks_path)
    else
      render :edit
    end
  end
  private
  def check_licences
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < UserController
  before_filter :check_password_submitted, :only => :update
  before_filter :check_user_level
  expose(:users){ current_account.users.order("id DESC").scoped{} }
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(users_users_path)
    else
      render :new
    end
  end

  def update
    if user.save
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(users_users_path)
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end

  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/views/users/trailers/_form.html.haml
= simple_form_for([:users, trailer], :html => {:class => 'form-horizontal' }) do |f|
  .mws-form-row
    %label.mws-form-label= t(:name)
    .mws-form-item
    = f.input :name, :label => false
  .mws-form-row
    %label.mws-form-label= t(:annual_inspection_pdf)
    .mws-form-item
      = f.input :annual_inspection_pdf, :label => false
  .mws-form-row
    %label.mws-form-label= t(:insurance_pdf)
    .mws-form-item
      = f.input :insurance_pdf, :label => false
  .mws-form-row
    %label.mws-form-label= t(:registration_pdf)
    .mws-form-item
      = f.input :registration_pdf, :label => false
  .mws-form-row
    %label.mws-form-label= t(:trailer_type)
    .mws-form-item
    = f.input :trailer_type, :collection => trailer_type_list,  :as => :select, include_blank: false, :label => false, prompt: "Choose a Trailer Type"
  .mws-form-row
    %label.mws-form-label= t(:length)
    .mws-form-item
    = f.input :length, :label => false
  .mws-form-row
    %label.mws-form-label= t(:width)
    .mws-form-item
    = f.input :width, :label => false
  .mws-form-row
    %label.mws-form-label= t(:height)
    .mws-form-item
    = f.input :height, :label => false
  .mws-form-row
    %label.mws-form-label= t(:gross_vehicle_weight_rating)
    .mws-form-item
    = f.input :gross_vehicle_weight_rating, :label => false
  .mws-form-row
    %label.mws-form-label= t(:suspension)
    .mws-form-item
    = f.input :suspension, :collection => suspension_list,  :as => :select, include_blank: false, :label => false
  .mws-form-row
    %label.mws-form-label= t(:axle_capacity)
    .mws-form-item
    = f.input :axle_capacity, :label => false
  .mws-form-row
    %label.mws-form-label= t(:wheels)
    .mws-form-item
    = f.input :wheels, :label => false
  .mws-form-row
    %label.mws-form-label= t(:tires)
    .mws-form-item
    = f.input :tires, :label => false
  .mws-form-row
    %label.mws-form-label= t(:vin)
    .mws-form-item
    = f.input :vehicle_identification_number, :label => false
  .mws-form-row
    %label.mws-form-label= t(:tag)
    .mws-form-item
    = f.input :vehicle_tag, :label => false
  .mws-form-row
    %label.mws-form-label= t(:annual_inspection)
    .mws-form-item
    = f.input :annual_inspection, :label => false, :input_html => { :class => 'datepicker'}
  .mws-form-row
    %label.mws-form-label= t(:year_build)
    .mws-form-item
    = f.input :year_build, :label => false
  .mws-form-row
    %label.mws-form-label= t(:manufacturer)
    .mws-form-item
    = f.input :manufacturer, :label => false
  .mws-form-row
    %label.mws-form-label= t(:vented)
    .mws-form-item
    = f.input :vented, :label => false
  .mws-form-row
    %label.mws-form-label= t(:photo)
    .mws-form-item
    = f.input :photo, :label => false
  .mws-form-row
    .mws-form-item
    = f.button :submit, :class => 'pull-right btn btn-info'

app/views/users/trailers/edit.html.haml
- content_for :pagetitle do 
  Update Trailer
  = trailer.name.titleize
%h1#main-heading
  Update Trailer

=render 'form'

app/views/users/trailers/index.html.haml
- content_for :pagetitle do 
  Trailers
.grid_8
  = link_to t(:add_trailer), new_users_trailer_path, :class => 'btn btn-info pull-right'
.mws-panel.grid_8
  .mws-panel-header
    %span
      Trailers
  .mws-panel-body.no-padding
    %table.mws-datatable-fn.mws-table
      %thead
        %tr
          %th
          %th= t(:name)
          %th= t(:tractor)
          %th= t(:driver)
          %th
          %th
      %tbody
        - trailers.each do |t|
          %tr
            %td= link_to t(:show), users_trailer_path(t), :class => 'btn btn-small btn-info'
            %td= link_to t.name.titleize, users_trailer_path(t)
            %td
              -t.truck.drivers.each_with_index do |d , index|
                - unless index == 0 
                  = "-"
                = link_to d.full_name, users_driver_path(d)
            %td
              -t.truck.drivers.each do |d|
                = link_to d.full_name, users_driver_path(d)
            %td
              - unless t.photo.blank?
                = image_tag t.photo.thumb.url, :width => '50'
              - else
                = image_tag 'myicons/trailer-icon-small.png', :width => '50'
            %td= link_to 'Edit', edit_users_trailer_path(t), :class => 'btn btn-small btn-info'

app/views/users/trailers/new.html.haml
- content_for :pagetitle do 
  New Trailer
  = trailer.name.titleize
%h1#main-heading
  Create Trailer

=render 'form'

app/views/users/trailers/show.html.haml
- content_for :pagetitle do 
  Trailer
  = trailer.name.titleize
.row-fluid
  .mws-panel.grid_2.pull-right
    - unless trailer.photo.blank?
      = image_tag trailer.photo.large_thumb, :width => '500', :class => 'img-polaroid'
    - else
      = image_tag 'myicons/trailer-icon.png', :width => '500', :class => 'img-polaroid'
  .mws-panel.grid_6
    .mws-panel-header
      = link_to 'Edit', edit_users_trailer_path(trailer), :class => 'btn btn-info pull-right'
      %span
        Trailer -
        = trailer.name.titleize
    .mws-panel-body.no-padding
      %ul.mws-summary.clearfix
        %li
          %span.key
            = t(:name)
          %span.val
            %span.text-nowrap= trailer.name
        %li
          %span.key
            = t(:annual_inspection_pdf)
          %span.val
            %span.text-nowrap
              - unless trailer.annual_inspection_pdf.blank?
                = link_to t(:annual_inspection_pdf), trailer.annual_inspection_pdf_url, :target => '_blanl'
              - else
                %span{:style => 'color:#F00'}= t(:annual_inspection_pdf)
        %li
          %span.key
            = t(:insurance_pdf)
          %span.val
            %span.text-nowrap
              - unless trailer.insurance_pdf.blank?
                = link_to t(:insurance_pdf), trailer.insurance_pdf_url, :target => '_blanl'
              - else
                %span{:style => 'color:#F00'}= t(:insurance_pdf)
        %li
          %span.key
            = t(:registration_pdf)
          %span.val
            %span.text-nowrap
              - unless trailer.registration_pdf.blank?
                = link_to t(:annual_inspection_pdf), trailer.registration_pdf_url, :target => '_blanl'
              - else
                %span{:style => 'color:#F00'}= t(:registration_pdf)
        %li
          %span.key
            = t(:trailer_type)
          %span.val
            %span.text-nowrap= trailer.trailer_type
        %li
          %span.key
            = t(:length)
          %span.val
            %span.text-nowrap= trailer.length
        %li
          %span.key
            = t(:width)
          %span.val
            %span.text-nowrap= trailer.width
        %li
          %span.key
            = t(:height)
          %span.val
            %span.text-nowrap= trailer.height
        %li
          %span.key
            = t(:gross_vehicle_weight_rating)
          %span.val
            %span.text-nowrap= trailer.gross_vehicle_weight_rating
        %li
          %span.key
            = t(:suspension)
          %span.val
            %span.text-nowrap= trailer.suspension
        %li
          %span.key
            = t(:axle_capacity)
          %span.val
            %span.text-nowrap= trailer.axle_capacity
        %li
          %span.key
            = t(:wheels)
          %span.val
            %span.text-nowrap= trailer.wheels
        %li
          %span.key
            = t(:tires)
          %span.val
            %span.text-nowrap= trailer.tires
        %li
          %span.key
            = t(:vin)
          %span.val
            %span.text-nowrap= trailer.vehicle_identification_number
        %li
          %span.key
            = t(:tag)
          %span.val
            %span.text-nowrap= trailer.vehicle_tag
        %li
          %span.key
            = t(:year_build)
          %span.val
            %span.text-nowrap= trailer.year_build
        %li
          %span.key
            = t(:manufacturer)
          %span.val
            %span.text-nowrap= trailer.manufacturer

%a{:name => "notes"}
.mws-panel.grid_6
  .mws-panel-header
    %span
      Notes
  .mws-panel-body.no-padding
    %ul.mws-summary.clearfix
      - Comment.where(:commenter_type => 'trailer').where(:commenter_id => trailer.id).order('id DESC').each do |c|
        %li
          %span.key
            - if c.user.photo_url
              = image_tag c.user.photo.thumb, :alt => c.user.full_name, :width => 25
            - else
              = image_tag '/assets/example/profile.jpg', :alt => c.user.full_name, :width => 25
            = c.user.name.titleize
          %span.val
            %span.text-nowrap
              =raw c.note

              .pull-right= c.created_at.in_time_zone('Eastern Time (US & Canada)').strftime('%D %r')
        .clear
.clear
.row-fluid
.mws-panel.grid_12
  .mws-panel-header
    %span Add Notes
  .mws-panel-body
    = form_for comment, :url => comments_path(:commenter_type => "trailer", :commenter_id => trailer.id) do |f|
      .mws-form-row
        %label.mws-form-label
          Note
        .mws-form-item
          = f.text_area :note, :class => 'cleditor'
        %br
        = f.button :submit, :class => 'btn btn-info'