config/routes.rb
Gotrucker::Application.routes.draw do
  devise_for :users, :controllers => { registrations:  'users/registrations',
                                      :sessions => "users/sessions",
                                      :passwords => 'users/passwords',
                                      :confirmations => 'users/confirmations'
  }
  authenticate :user do
    namespace :users do
      resources :ui
      resources :users
      resources :accounts, :only => [:show, :edit, :update]
      resources :drivers
      resources :profile, :only => [:edit, :update]
      resources :trucks
      resources :trailers
      resources :brokers do
        collection { post :import }
      end
      match "/shipments/delete" => "shipments#delete", :as => :shipments_delete
      resources :shipments
      resources :receipts
      resources :repairs
      match '/invoices/:id/pdf' => 'invoices#pdf', :as => :invoices_pdf
      resources :invoices
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

   devise_for :admins, :controllers => { registrations: 'admins/registrations',
                                       :sessions => "admins/sessions",
                                       :passwords => 'admins/passwords',
                                       :confirmations => 'admins/confirmations'
   }
   authenticate :admin do
     namespace :admins do
       resources :ui
       resources :accounts
       resources :admins
       resources :brokers
       resources :drivers
       resources :leads
       resources :plans
       resources :profile, :only => [:edit, :update]
       resources :receipts
       resources :repairs
       resources :shipments
       resources :trailers
       resources :trucks
       resources :users
       post '/users/login_as' => 'users#login_as', as: :login_as_user
       get '/dashboard' => 'dashboards#index', as: :dashboard
       get '/' => 'dashboards#index'
     end
   end

#   namespace :api do
#     namespace :internal do
#       namespace :v1 do
#         resources :users
#         resources :drivers
#         resources :trucks
#         resources :trailers
#         resources :brokers
#         resources :shipments
#         resources :receipts
#         resources :repairs
#         resources :invoices
#       end
#     end
#   end
  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us
  match '/thanks' => 'leads#thanks', :as => :thanks
  match "/prices" => "pages#prices", :as => :prices
  match "/about_us" => "pages#about_us", :as => :about_us
  match "/test" => "pages#test", :as => :test
  root :to => 'pages#index'
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :truck
  belongs_to :account
  has_many :receipts
  has_many :comments, :as => :commenter
  attr_accessible  :truck_id, :first_name, :last_name, :address, :address2, :city, :state, :zip, :cell, :email, :ssn,  :photo, :drivers_license, :pay_rate, :hire_date, :active, :bank_name, :bank_account_number, :bank_rauting_number, :double_triple_trailers, :passenger, :tank_vehicle, :hazardous_materials, :combination_of_tank_vehicle_and_hazardous_materials, :drivers_license_photo, :account_id, :medical_long_form_pdf, :release_date, :twic_card

  before_validation { |driver| driver.zip = zip.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |driver| driver.cell = cell.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |driver| driver.ssn = ssn.to_s.gsub(/[^0-9]/, "").to_s }

  mount_uploader :photo, PhotoUploader
  mount_uploader :drivers_license_photo, PhotoUploader
  mount_uploader :medical_long_form_pdf, FileUploader

  def name
    full_name
  end
  def full_name
    first_name + ' ' + last_name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  has_many :comments
  has_many :comments, :as => :commenter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :photo, :phone, :active, :is_owner, :is_primary, :account_id, :plan_slug, :s, :account_attributes, :subscriptions_type

  validates_uniqueness_of :email
  validates_presence_of :password, :if => :should_validate_password?

  attr_accessor :updating_password
  attr_accessor :plan_slug
  attr_accessor :s
  attr_accessor :subscriptions_type
  accepts_nested_attributes_for :account
  mount_uploader :photo, PhotoUploader

  def name
    full_name
  end

  def full_name
    first_name + ' ' + last_name
  end
  def should_validate_password?
      updating_password || new_record?
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminController
  before_filter :check_password_submitted, :only => :update
  expose(:users) {User.order("id DESC").scoped{}}
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(admins_user_path(user))
    else
      render :new
    end
  end

  def update
    if user.update_attributes(params[:user])
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(admins_user_path(user))
    else
      render :edit
    end
  end
  def login_as
    sign_in(User.find(params[:id]), :bypass => true)
    redirect_to users_dashboard_path
  end
  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/api/internal/v1/users_controller.rb
class Api::Internal::V1::UsersController < ApiController
  expose(:users){ User.all }
  expose(:user){ User.find(params[:id]) }
  respond_to :json
  before_filter :check_api_key


  private
  def check_api_key
    unless params['api_key'] == ENV['INTERNAL_API_KEY']
      respond_with({:result => 'Invalid API Key'})
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  expose(:current_account){ current_user.account }
  layout 'user_application'
  before_filter :check_user_active
  before_filter :check_unpaid_invoices
  private
    def check_user_active
      unless current_user.active
        flash[:notice]= t(:user_not_active)
        sign_out current_user
        redirect_to new_user_session_path
      end
    end
    def check_unpaid_invoices
      if current_account.invoices.count > 0
        if current_account.invoices.where(:paid_status => 'unpaid').where("created_at <= ?", Time.now - 30.days).count > 0
          flash[:error]= 'There are unpaid invoices over 30 days'
        end
      end
  end
end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < UserController
  before_filter :check_user_level
  expose(:account) {current_account}

  def create
    if account.save
      flash[:notice] = t(:account_was_successfully_created)
      redirect_to(users_account_path(current_account))
    else
      render :new
    end
  end

  def update
    if account.update_attributes(params[:account])
      flash[:notice] = t(:account_was_successfully_updated)
      redirect_to(users_account_path(current_account))
    else
      render :edit
    end
  end
  private
  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/controllers/users/brokers_controller.rb
class Users::BrokersController < UserController
  require 'csv'
  expose(:brokers){ current_account.brokers.order("id DESC").scoped{} }
  expose(:broker)
  expose(:comment) { broker.comments.new}

  def create
    if broker.save
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
    else
      render :new
    end
  end

  def update
    if broker.save
      flash[:notice] = t(:broker_was_successfully_updated)
      redirect_to(users_brokers_path)
    else
      render :edit
    end
  end


  def import
    puts params
    csv_text = File.read('public/brokers.csv')
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
        current_account.brokers.create!(row.to_hash)
    end
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
  end 
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:drivers){ current_account.drivers.where(:active => true).order("id DESC").scoped{} }
end

app/controllers/users/drivers_controller.rb
class Users::DriversController < UserController
  expose(:drivers){ current_account.drivers.order("id DESC").scoped{} }
  expose(:driver)
  expose(:comment) { driver.comments.new}

  def create
    if driver.save
      flash[:notice] = t(:driver_was_successfully_created)
      redirect_to(users_drivers_path)
    else
      render :new
    end
  end

  def update
    if driver.save
      flash[:notice] = t(:driver_was_successfully_updated)
      redirect_to(users_drivers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/invoices_controller.rb
class Users::InvoicesController < UserController
  expose(:invoices){ current_account.invoices.order("id DESC").scoped{} }
  expose(:invoice)
  expose(:comment) { invoice.comments.new}
  expose(:shipment) {
    if params[:shipment]
      current_account.shipments.find(params[:shipment])
    else
      false
    end
  }

  def create
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_created)
      redirect_to(users_invoices_path)
    else
      render :new
    end
  end

  def update
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_updated)
      redirect_to(users_invoices_path)
    else
      render :edit
    end
  end
  
  def pdf
    render :layout => 'invoice'
    #render :layout => false  
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'user_login'
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < UserController
  before_filter :check_password_submitted, :only => :update
  expose(:user){ current_user }
  def update
    if user.update_attributes(params[:user])
      sign_in(current_user, :bypass => true)
      flash[:notice] = t(:profile_was_successfully_updated)
      redirect_to users_dashboard_path
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/users/receipts_controller.rb
class Users::ReceiptsController < UserController
  expose(:receipts){ current_account.receipts.order("id DESC").scoped{} }
  expose(:receipt)
  expose(:comment) { receipt.comments.new}

  def create
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_created)
      redirect_to(users_receipts_path)
    else
      render :new
    end
  end

  def update
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_updated)
      redirect_to(users_receipts_path)
    else
      render :edit
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 #layout 'application'
 before_filter :before_create_account, :only => [:create]
 after_filter :account_must_have_a_plan, :only => [:create]
 expose(:plan){Plan.find_by_slug(params[:plan])}
 def new
  redirect_to user_dashboard_path if current_user
  resource = build_resource({})
  resource.build_account
  resource.account.build_subscription
  resource.plan_slug = plan.slug if plan
  respond_with resource
 end

 def after_inactive_sign_up_path_for(resource)
   users_dashboard_path
 end

 def after_sign_up_path_for(resource)
   sign_in(resource)
   users_dashboard_path
 end

 private
 def before_create_account
    params[:user][:is_owner] = true
    params[:user][:is_primary] = true
 end

 def account_must_have_a_plan
   unless resource.new_record?
     s = Subscription.find_by_key(params[:user][:s])
     plan = Plan.find_by_slug(s.item_number)

     params[:user][:subscriptions_type] = 'monthly'
     if params[:user][:subscriptions_type] == 'monthly'
       price = plan.monthy_price
     else
       price = plan.yearly_price
     end
     s.update_attributes(:account_id => resource.account.id, :plan_id => plan.id, :name => plan.name, :price => price, :slug => plan.slug, :licenses => plan.licenses, :subscriptions_type => params[:user][:subscriptions_type]  )
   end
 end

end

app/controllers/users/repairs_controller.rb
class Users::RepairsController < UserController
  expose(:repairs){ current_account.repairs.order("id DESC").scoped{} }
  expose(:repair)
  expose(:comment) { repair.comments.new}

  def create
    if repair.save
      flash[:notice] = t(:repair_was_successfully_created)
      redirect_to(users_repairs_path)
    else
      render :new
    end
  end

  def update
    if repair.save
      flash[:notice] = t(:repair_was_successfully_updated)
      redirect_to(users_repairs_path)
    else
      render :edit
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'user_login'
  private
  def after_sign_in_path_for(resource)
    users_dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/users/shipments_controller.rb
class Users::ShipmentsController < UserController
  expose(:shipments){ current_account.shipments.order("id DESC").scoped{} }
  expose(:shipment)
  expose(:comment) { shipment.comments.new}

  def create
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_created)
      redirect_to(users_shipments_path)
    else
      render :new
    end
  end

  def update
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_updated)
      redirect_to(users_shipments_path)
    else
      render :edit
    end
  end
   def delete
     s = Shipment.find(params[:format])
     s.delete
      flash[:notice] = t(:shipment_was_successfully_deleted)
      redirect_to(users_shipments_path)
   end
end

app/controllers/users/trailers_controller.rb
class Users::TrailersController < UserController
  expose(:trailers){ current_account.trailers.order("id DESC").scoped{} }
  expose(:trailer)
  expose(:comment) { trailer.comments.new}

  def create
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_created)
      redirect_to(users_trailers_path)
    else
      render :new
    end
  end

  def update
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_updated)
      redirect_to(users_trailers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/trucks_controller.rb
class Users::TrucksController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:truck)
  expose(:comment) { truck.comments.new}

  def create
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_created)
      redirect_to(users_trucks_path)
    else
      render :new
    end
  end

  def update
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_updated)
      redirect_to(users_trucks_path)
    else
      render :edit
    end
  end
  private
  def check_licences
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < UserController
  before_filter :check_password_submitted, :only => :update
  before_filter :check_user_level
  expose(:users){ current_account.users.order("id DESC").scoped{} }
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(users_users_path)
    else
      render :new
    end
  end

  def update
    if user.save
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(users_users_path)
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end

  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/views/users/drivers/_form.html.haml
= simple_form_for([:users, driver], :html => {:class => 'form-horizontal' }) do |f|
  .mws-form-row
    %label.mws-form-label= t(:first_name)
    .mws-form-item
    = f.input :first_name, :label => false
  .mws-form-row
    %label.mws-form-label= t(:last_name)
    .mws-form-item
    = f.input :last_name, :label => false
  .mws-form-row
    %label.mws-form-label= t(:email)
    .mws-form-item
    = f.input :email, :label => false
  .mws-form-row
    %label.mws-form-label= t(:truck)
    .mws-form-item
    = f.association :truck, collection: current_account.trucks.all(order: 'name'), prompt: "Choose a Truck", :label => false, include_blank: true
  .mws-form-row
    %label.mws-form-label= t(:address)
    .mws-form-item
    = f.input :address, :label => false
  .mws-form-row
    %label.mws-form-label= t(:address2)
    .mws-form-item
    = f.input :address2, :label => false
  .mws-form-row
    %label.mws-form-label= t(:city)
    .mws-form-item
    = f.input :city, :label => false
  .mws-form-row
    %label.mws-form-label= t(:state)
    .mws-form-item
    = f.input :state, :collection => us_states,  :as => :select, include_blank: true, :label => false
  .mws-form-row
    %label.mws-form-label= t(:zip)
    .mws-form-item
    = f.input :zip, :label => false
  .mws-form-row
    %label.mws-form-label= t(:cell)
    .mws-form-item
    = f.input :cell, :label => false
  .mws-form-row
    %label.mws-form-label= t(:ssn)
    .mws-form-item
    = f.input :ssn, :label => false
  .mws-form-row
    %label.mws-form-label= t(:drivers_license)
    .mws-form-item
    = f.input :drivers_license, :label => false
  .mws-form-row
    %label.mws-form-label= t(:pay_rate)
    .mws-form-item
    = f.input :pay_rate, :label => false
  .mws-form-row
    %label.mws-form-label= t(:hire_date)
    .mws-form-item
    = f.input :hire_date, :label => false, :input_html => { :class => 'datepicker'}
  .mws-form-row
    %label.mws-form-label= t(:release_date)
    .mws-form-item
    = f.input :release_date, :label => false, :input_html => { :class => 'datepicker'}
  .mws-form-row
    %label.mws-form-label= t(:active)
    .mws-form-item
    = f.input :active, :label => false
  .mws-form-row
    %label.mws-form-label= t(:bank_name)
    .mws-form-item
    = f.input :bank_name, :label => false
  .mws-form-row
    %label.mws-form-label= t(:bank_account_number)
    .mws-form-item
    = f.input :bank_account_number, :label => false
  .mws-form-row
    %label.mws-form-label= t(:bank_routing_number)
    .mws-form-item
    = f.input :bank_rauting_number, :label => false
  .mws-form-row
    %label.mws-form-label= t(:double_triple_trailers)
    .mws-form-item
    = f.input :double_triple_trailers, :label => false
  .mws-form-row
    %label.mws-form-label= t(:passenger)
    .mws-form-item
    = f.input :passenger, :label => false
  .mws-form-row
    %label.mws-form-label= t(:tank_vehicle)
    .mws-form-item
    = f.input :tank_vehicle, :label => false
  .mws-form-row
    %label.mws-form-label= t(:hazardous_materials)
    .mws-form-item
    = f.input :hazardous_materials, :label => false
  .mws-form-row
    %label.mws-form-label= t(:combination_of_tank_vehicle_and_hazardous_materials)
    .mws-form-item
    = f.input :combination_of_tank_vehicle_and_hazardous_materials, :label => false
  .mws-form-row
    %label.mws-form-label= t(:twic_card)
    .mws-form-item
    = f.input :twic_card, :label => false
  .mws-form-row
    %label.mws-form-label= t(:photo)
    .mws-form-item
    = f.input :photo, :label => false
  .mws-form-row
    %label.mws-form-label= t(:drivers_license_photo)
    .mws-form-item
    = f.input :drivers_license_photo, :label => false
  .mws-form-row
    %label.mws-form-label= t(:medical_long_form_pdf)
    .mws-form-item
    = f.input :medical_long_form_pdf, :label => false
  .mws-form-row
    .mws-form-item
    = f.button :submit, :class => 'pull-right btn btn-info'

app/views/users/drivers/edit.html.haml
- content_for :pagetitle do 
  Edit Driver
%h1#main-heading
  Update Driver

=render 'form'

app/views/users/drivers/index.html.haml
- content_for :pagetitle do 
  Drivers
.grid_8
  = link_to t(:add_driver), new_users_driver_path, :class => 'btn btn-info pull-right'
.mws-panel.grid_8
  .mws-panel-header
    %span
      Drivers
  .mws-panel-body.no-padding
    %table.mws-datatable-fn.mws-table
      %thead
        %tr
          %th
          %th=t(:name)
          %th=t(:truck)
          %th=t(:trailer)
          %th=t(:cell)
          %th=t(:email)
          %th=t(:active)
          %th
          %th
      %tbody
        - drivers.each do |d|
          %tr
            %td= link_to t(:show), users_driver_path(d), :class => 'btn btn-small btn-info'
            %td= link_to d.full_name.titleize, users_driver_path(d)
            %td
              = link_to d.truck.name.titleize, users_truck_path(d.truck) if d.truck
            %td
              = link_to d.truck.trailer.name.titleize, users_trailer_path(d.truck.trailer) if d.truck and d.truck.trailer
            %td= number_to_phone(d.cell)
            %td= mail_to d.email
            %td
              -if d.active
                .badge.badge-success= t(:active)
              - else
                .badge.badge-important= t(:inactive)
            %td
              - if d.photo?
                = image_tag d.photo.thumb.url, :width => '50'
              - else
                = image_tag 'myicons/driver-icon-small.png', :width => '50'
            %td= link_to 'Edit', edit_users_driver_path(d), :class => 'btn btn-small btn-info'

app/views/users/drivers/new.html.haml
- content_for :pagetitle do 
  New Driver
%h1#main-heading
  Create Driver

=render 'form'

app/views/users/drivers/show.html.haml
- content_for :pagetitle do
  Driver
  = driver.full_name.titleize
.row-fluid
  .mws-panel.grid_2.pull-right
    - if driver.photo?
      = image_tag driver.photo.large_thumb, :width => '400', :alt => driver.name, :class => 'img-polaroid'
    - else
      = image_tag 'myicons/driver-icon.png', :width => '400', :class => 'img-polaroid'
    - if driver.drivers_license_photo?
      = image_tag driver.drivers_license_photo.large_thumb, :width => '400', :alt => driver.name, :class => 'img-polaroid'
    - else
      = image_tag 'myicons/drivers-license-icon.png', :width => '400', :class => 'img-polaroid'
  .mws-panel.grid_6
    .mws-panel-header
      = link_to 'Edit', edit_users_driver_path(driver), :class => 'btn btn-info pull-right'
      %span
        Driver -
        = driver.full_name.titleize
    .mws-panel-body.no-padding
      %ul.mws-summary.clearfix
        %li
          %span.key
            = t(:name)
          %span.val
            %span.text-nowrap= driver.full_name
        %li
          %span.key
            = t(:medical_long_form_pdf)
          %span.val
            %span.text-nowrap
              - unless driver.medical_long_form_pdf.blank?
                = link_to t(:medical_long_form_pdf), driver.medical_long_form_pdf_url, :target => '_blanl'
              - else
                %span{:style => 'color:#F00'}= t(:medical_long_form_pdf)
        %li
          %span.key
            = t(:truck)
          %span.val
            %span.text-nowrap
              = link_to driver.truck.name, users_truck_path(driver.truck) if driver.truck
        %li
          %span.key
            = t(:trailer)
          %span.val
            %span.text-nowrap
              = link_to driver.truck.trailer.name, users_trailer_path(driver.truck.trailer) if driver.truck and driver.truck.trailer
        %li
          %span.key
            = t(:address)
          %span.val
            %span.text-nowrap
              - address = driver.address + ' ' + driver.address2 + ' ' + driver.city  + ' ' + driver.state  + ' ' + driver.zip
              = address
              = link_to 'https://maps.google.com/maps?q='+ address  +'&t=m&z=17', :target => '_blank' do
                %i.icol32-map2
        %li
          %span.key
            = t(:email)
          %span.val
            %span.text-nowrap
              = mail_to driver.email
        %li
          %span.key
            = t(:cell)
          %span.val
            %span.text-nowrap= number_to_phone(driver.cell)
        %li
          %span.key
            = t(:ssn)
          %span.val
            %span.text-nowrap= driver.ssn
        %li
          %span.key
            = t(:drivers_license)
          %span.val
            %span.text-nowrap= driver.drivers_license
        %li
          %span.key
            = t(:pay_rate)
          %span.val
            %span.text-nowrap= driver.pay_rate
        %li
          %span.key
            = t(:hire_date)
          %span.val
            %span.text-nowrap= driver.hire_date
        %li
          %span.key
            = t(:release_date)
          %span.val
            %span.text-nowrap= driver.release_date
        %li
          %span.key
            = t(:active)
          %span.val
            %span.text-nowrap= driver.active
        %li
          %span.key
            = t(:bank_name)
          %span.val
            %span.text-nowrap= driver.bank_name
        %li
          %span.key
            = t(:bank_account_number)
          %span.val
            %span.text-nowrap= driver.bank_account_number
        %li
          %span.key
            = t(:bank_routing_number)
          %span.val
            %span.text-nowrap= driver.bank_rauting_number
        %li
          %span.key
            = t(:endorsements)
          %span.val
            %span.text-nowrap
              - if driver.double_triple_trailers
                .badge.badge-success= t(:double_triple_trailers)
              - if driver.passenger
                .badge.badge-success= t(:passenger)
              - if driver.tank_vehicle
                .badge.badge-success= t(:tank_vehicle)
              - if driver.hazardous_materials
                .badge.badge-success= t(:hazardous_materials)
              - if driver.combination_of_tank_vehicle_and_hazardous_materials
                .badge.badge-success= t(:combination_of_tank_vehicle_and_hazardous_materials)
              - if driver.twic_card
                .badge.badge-success= t(:twic_card)
  .mws-panel.grid_6
    .mws-panel-header
      %span
        Notes
    .mws-panel-body.no-padding
      %ul.mws-summary.clearfix
        - Comment.where(:commenter_type => 'driver').where(:commenter_id => driver.id).order('id DESC').each do |c|
          %li
            %span.key
              - if c.user.photo_url
                = image_tag c.user.photo.thumb, :alt => c.user.full_name, :width => 25
              - else
                = image_tag '/assets/example/profile.jpg', :alt => c.user.full_name, :width => 25
              = c.user.name.titleize
            %span.val
              %span.text-nowrap
                =raw c.note

                .pull-right= c.created_at.in_time_zone('Eastern Time (US & Canada)').strftime('%D %r')
          .clear
.clear
.row-fluid
.mws-panel.grid_12
  .mws-panel-header
    %span Add Notes
  .mws-panel-body
    = form_for comment, :url => comments_path(:commenter_type => "driver", :commenter_id => driver.id) do |f|
      .mws-form-row
        %label.mws-form-label
          Note
        .mws-form-item
          = f.text_area :note, :class => 'cleditor'
        %br
        = f.button :submit, :class => 'btn btn-info'