config/routes.rb
Gotrucker::Application.routes.draw do
  devise_for :users, :controllers => { registrations:  'users/registrations',
                                      :sessions => "users/sessions",
                                      :passwords => 'users/passwords',
                                      :confirmations => 'users/confirmations'
  }
  authenticate :user do
    namespace :users do
      resources :ui
      resources :users
      resources :accounts, :only => [:show, :edit, :update]
      resources :drivers
      resources :profile, :only => [:edit, :update]
      resources :trucks
      resources :trailers
      resources :brokers do
        collection { post :import }
      end
      match "/shipments/delete" => "shipments#delete", :as => :shipments_delete
      resources :shipments
      resources :receipts
      resources :repairs
      match '/invoices/:id/pdf' => 'invoices#pdf', :as => :invoices_pdf
      resources :invoices
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

   devise_for :admins, :controllers => { registrations: 'admins/registrations',
                                       :sessions => "admins/sessions",
                                       :passwords => 'admins/passwords',
                                       :confirmations => 'admins/confirmations'
   }
   authenticate :admin do
     namespace :admins do
       resources :ui
       resources :accounts
       resources :admins
       resources :brokers
       resources :drivers
       resources :leads
       resources :plans
       resources :profile, :only => [:edit, :update]
       resources :receipts
       resources :repairs
       resources :shipments
       resources :trailers
       resources :trucks
       resources :users
       post '/users/login_as' => 'users#login_as', as: :login_as_user
       get '/dashboard' => 'dashboards#index', as: :dashboard
       get '/' => 'dashboards#index'
     end
   end

#   namespace :api do
#     namespace :internal do
#       namespace :v1 do
#         resources :users
#         resources :drivers
#         resources :trucks
#         resources :trailers
#         resources :brokers
#         resources :shipments
#         resources :receipts
#         resources :repairs
#         resources :invoices
#       end
#     end
#   end
  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us
  match '/thanks' => 'leads#thanks', :as => :thanks
  match "/prices" => "pages#prices", :as => :prices
  match "/about_us" => "pages#about_us", :as => :about_us
  match "/test" => "pages#test", :as => :test
  root :to => 'pages#index'
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  belongs_to :account
  belongs_to :broker
  belongs_to :truck
  belongs_to :trailer
  belongs_to :new_trailer, :foreign_key => 'testing',:class_name => "Trailer"
  has_one :invoice
  has_many :comments, :as => :commenter

  attr_accessible :broker_id, :truck_id, :trailer_id, :load_number, :price, :miles, :pick_up_location_address, :pick_up_location_address2, :pick_up_location_city, :pick_up_location_state, :pick_up_location_zip, :delivery_location_address, :delivery_location_address2, :delivery_location_city, :delivery_location_state, :delivery_location_zip, :number_of_stops, :notes, :pick_up_date, :deliver_date, :status, :weight, :drivers_notes, :packing, :seal_number, :double_triple_trailers, :passenger, :tank_vehicls, :hazardous_materials, :suspension, :paid_status, :paid_date, :load_conformation, :delivery_location_phone, :pick_up_location_phone, :equipment_type, :size_of_trailer, :pallets_pisses, :pick_up_number, :delivery_number, :pick_up_earlier_time, :pick_up_lateest_time, :pick_up_appointment, :delivery_earlier_time, :delivery_lateest_time, :trailer_type, :tank_vehicle, :delivery_appointment, :load_conformation_pdf, :account_id, :price2, :miles2, :weight2 ,:testing, :pick_up_company, :delivery_company, :bill_of_lading_pdf, :twic_card

  before_validation { |shipment| shipment.miles = miles.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |shipment| shipment.delivery_location_zip = delivery_location_zip.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |shipment| shipment.number_of_stops = number_of_stops.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |shipment| shipment.delivery_location_phone = delivery_location_phone.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |shipment| shipment.delivery_location_zip = delivery_location_zip.to_s.gsub(/[^0-9]-/, "").to_s }
  before_validation { |shipment| shipment.pick_up_location_phone = pick_up_location_phone.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |shipment| shipment.pick_up_location_zip = pick_up_location_zip.to_s.gsub(/[^0-9]-/, "").to_s }

  mount_uploader :load_conformation_pdf, FileUploader
  mount_uploader :bill_of_lading_pdf, FileUploader

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminController
  before_filter :check_password_submitted, :only => :update
  expose(:users) {User.order("id DESC").scoped{}}
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(admins_user_path(user))
    else
      render :new
    end
  end

  def update
    if user.update_attributes(params[:user])
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(admins_user_path(user))
    else
      render :edit
    end
  end
  def login_as
    sign_in(User.find(params[:id]), :bypass => true)
    redirect_to users_dashboard_path
  end
  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/api/internal/v1/users_controller.rb
class Api::Internal::V1::UsersController < ApiController
  expose(:users){ User.all }
  expose(:user){ User.find(params[:id]) }
  respond_to :json
  before_filter :check_api_key


  private
  def check_api_key
    unless params['api_key'] == ENV['INTERNAL_API_KEY']
      respond_with({:result => 'Invalid API Key'})
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  expose(:current_account){ current_user.account }
  layout 'user_application'
  before_filter :check_user_active
  before_filter :check_unpaid_invoices
  private
    def check_user_active
      unless current_user.active
        flash[:notice]= t(:user_not_active)
        sign_out current_user
        redirect_to new_user_session_path
      end
    end
    def check_unpaid_invoices
      if current_account.invoices.count > 0
        if current_account.invoices.where(:paid_status => 'unpaid').where("created_at <= ?", Time.now - 30.days).count > 0
          flash[:error]= 'There are unpaid invoices over 30 days'
        end
      end
  end
end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < UserController
  before_filter :check_user_level
  expose(:account) {current_account}

  def create
    if account.save
      flash[:notice] = t(:account_was_successfully_created)
      redirect_to(users_account_path(current_account))
    else
      render :new
    end
  end

  def update
    if account.update_attributes(params[:account])
      flash[:notice] = t(:account_was_successfully_updated)
      redirect_to(users_account_path(current_account))
    else
      render :edit
    end
  end
  private
  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/controllers/users/brokers_controller.rb
class Users::BrokersController < UserController
  require 'csv'
  expose(:brokers){ current_account.brokers.order("id DESC").scoped{} }
  expose(:broker)
  expose(:comment) { broker.comments.new}

  def create
    if broker.save
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
    else
      render :new
    end
  end

  def update
    if broker.save
      flash[:notice] = t(:broker_was_successfully_updated)
      redirect_to(users_brokers_path)
    else
      render :edit
    end
  end


  def import
    puts params
    csv_text = File.read('public/brokers.csv')
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
        current_account.brokers.create!(row.to_hash)
    end
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
  end 
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:drivers){ current_account.drivers.where(:active => true).order("id DESC").scoped{} }
end

app/controllers/users/drivers_controller.rb
class Users::DriversController < UserController
  expose(:drivers){ current_account.drivers.order("id DESC").scoped{} }
  expose(:driver)
  expose(:comment) { driver.comments.new}

  def create
    if driver.save
      flash[:notice] = t(:driver_was_successfully_created)
      redirect_to(users_drivers_path)
    else
      render :new
    end
  end

  def update
    if driver.save
      flash[:notice] = t(:driver_was_successfully_updated)
      redirect_to(users_drivers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/invoices_controller.rb
class Users::InvoicesController < UserController
  expose(:invoices){ current_account.invoices.order("id DESC").scoped{} }
  expose(:invoice)
  expose(:comment) { invoice.comments.new}
  expose(:shipment) {
    if params[:shipment]
      current_account.shipments.find(params[:shipment])
    else
      false
    end
  }

  def create
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_created)
      redirect_to(users_invoices_path)
    else
      render :new
    end
  end

  def update
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_updated)
      redirect_to(users_invoices_path)
    else
      render :edit
    end
  end
  
  def pdf
    render :layout => 'invoice'
    #render :layout => false  
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'user_login'
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < UserController
  before_filter :check_password_submitted, :only => :update
  expose(:user){ current_user }
  def update
    if user.update_attributes(params[:user])
      sign_in(current_user, :bypass => true)
      flash[:notice] = t(:profile_was_successfully_updated)
      redirect_to users_dashboard_path
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/users/receipts_controller.rb
class Users::ReceiptsController < UserController
  expose(:receipts){ current_account.receipts.order("id DESC").scoped{} }
  expose(:receipt)
  expose(:comment) { receipt.comments.new}

  def create
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_created)
      redirect_to(users_receipts_path)
    else
      render :new
    end
  end

  def update
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_updated)
      redirect_to(users_receipts_path)
    else
      render :edit
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 #layout 'application'
 before_filter :before_create_account, :only => [:create]
 after_filter :account_must_have_a_plan, :only => [:create]
 expose(:plan){Plan.find_by_slug(params[:plan])}
 def new
  redirect_to user_dashboard_path if current_user
  resource = build_resource({})
  resource.build_account
  resource.account.build_subscription
  resource.plan_slug = plan.slug if plan
  respond_with resource
 end

 def after_inactive_sign_up_path_for(resource)
   users_dashboard_path
 end

 def after_sign_up_path_for(resource)
   sign_in(resource)
   users_dashboard_path
 end

 private
 def before_create_account
    params[:user][:is_owner] = true
    params[:user][:is_primary] = true
 end

 def account_must_have_a_plan
   unless resource.new_record?
     s = Subscription.find_by_key(params[:user][:s])
     plan = Plan.find_by_slug(s.item_number)

     params[:user][:subscriptions_type] = 'monthly'
     if params[:user][:subscriptions_type] == 'monthly'
       price = plan.monthy_price
     else
       price = plan.yearly_price
     end
     s.update_attributes(:account_id => resource.account.id, :plan_id => plan.id, :name => plan.name, :price => price, :slug => plan.slug, :licenses => plan.licenses, :subscriptions_type => params[:user][:subscriptions_type]  )
   end
 end

end

app/controllers/users/repairs_controller.rb
class Users::RepairsController < UserController
  expose(:repairs){ current_account.repairs.order("id DESC").scoped{} }
  expose(:repair)
  expose(:comment) { repair.comments.new}

  def create
    if repair.save
      flash[:notice] = t(:repair_was_successfully_created)
      redirect_to(users_repairs_path)
    else
      render :new
    end
  end

  def update
    if repair.save
      flash[:notice] = t(:repair_was_successfully_updated)
      redirect_to(users_repairs_path)
    else
      render :edit
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'user_login'
  private
  def after_sign_in_path_for(resource)
    users_dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/users/shipments_controller.rb
class Users::ShipmentsController < UserController
  expose(:shipments){ current_account.shipments.order("id DESC").scoped{} }
  expose(:shipment)
  expose(:comment) { shipment.comments.new}

  def create
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_created)
      redirect_to(users_shipments_path)
    else
      render :new
    end
  end

  def update
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_updated)
      redirect_to(users_shipments_path)
    else
      render :edit
    end
  end
   def delete
     s = Shipment.find(params[:format])
     s.delete
      flash[:notice] = t(:shipment_was_successfully_deleted)
      redirect_to(users_shipments_path)
   end
end

app/controllers/users/trailers_controller.rb
class Users::TrailersController < UserController
  expose(:trailers){ current_account.trailers.order("id DESC").scoped{} }
  expose(:trailer)
  expose(:comment) { trailer.comments.new}

  def create
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_created)
      redirect_to(users_trailers_path)
    else
      render :new
    end
  end

  def update
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_updated)
      redirect_to(users_trailers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/trucks_controller.rb
class Users::TrucksController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:truck)
  expose(:comment) { truck.comments.new}

  def create
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_created)
      redirect_to(users_trucks_path)
    else
      render :new
    end
  end

  def update
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_updated)
      redirect_to(users_trucks_path)
    else
      render :edit
    end
  end
  private
  def check_licences
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < UserController
  before_filter :check_password_submitted, :only => :update
  before_filter :check_user_level
  expose(:users){ current_account.users.order("id DESC").scoped{} }
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(users_users_path)
    else
      render :new
    end
  end

  def update
    if user.save
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(users_users_path)
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end

  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/views/users/shipments/edit.html.haml
- content_for :pagetitle do 
  Edit Shipment
%h1#main-heading
  Update Shipment

=render 'form'

app/views/users/shipments/index.html.haml
- content_for :pagetitle do 
  Shipments
.grid_8
  = link_to t(:add_shipment), new_users_shipment_path, :class => 'btn btn-info pull-right'
.mws-panel.grid_8
  .mws-panel-header
    %span
      Shipments
  .mws-panel-body.no-padding
    %table.mws-datatable-fn.mws-table
      %thead
        %tr
          %th
          %th= t(:broker)
          %th= t(:truck)
          %th= t(:trailer)
          %th= t(:pick_up_date)
          %th= t(:deliver_date)
          %th= t(:price)
          %th= t(:load_conformation)
          %th= t(:load_number)
          %th= t(:status)
          %th= t(:invoiced_date)
          %th= t(:invoiced_status)
          %th
      %tbody
        - shipments.each do |s|
          %tr
            %td= link_to t(:show), users_shipment_path(s), :class => 'btn btn-small btn-info'
            %td
              = link_to s.broker.name, users_broker_path(s.broker) if s.broker
            %td
              = link_to s.truck.name, users_truck_path(s.truck) if s.truck
            %td
              = link_to s.trailer.name, users_trailer_path(s.trailer) if s.trailer
            %td= s.pick_up_date
            %td= s.deliver_date
            %td= number_to_currency(s.price)
            %td
              - unless s.load_conformation_pdf.blank?
                = link_to 'load_conformation_pdf', s.load_conformation_pdf_url, :target => '_blanl'
              - else
                %span{:style => 'color:#F00'}= t(:load_conformation)
            %td= s.load_number
            %td= s.status
            %td= s.invoice.created_at.strftime('%D') if s.invoice
            %td= s.invoice.paid_status if s.invoice

            %td
              = link_to 'Edit', edit_users_shipment_path(s), :class => 'btn btn-small btn-info'
              - if s.invoice
                = link_to 'Invoice', users_invoice_path(s.invoice), :class => 'btn btn-small btn-info'
              - else
                = link_to 'Invoice', new_users_invoice_path(:shipment => s), :class => 'btn btn-small btn-warning'
              = link_to 'Delete Shipment', users_shipments_delete_path(s), :confirm => 'Are you sure?' , :class => 'btn btn-small btn-danger'

  = link_to t(:has_not_invoice),'#', :class => 'btn btn-warning'
  = link_to t(:has_invoice),'#', :class => 'btn btn-info'

app/views/users/shipments/new.html.haml
- content_for :pagetitle do 
  New Shipment
%h1#main-heading
  Create Shipment

=render 'form'

app/views/users/shipments/show.html.haml
- content_for :pagetitle do 
  Shipment
  = shipment.broker.name.titleize if shipment.broker
  = shipment.load_number
  = shipment.truck.name.titleize if shipment.truck
  = shipment.pick_up_date

.mws-panel.grid_12
  .mws-panel-header
    = link_to 'Delete Shipment', users_shipments_delete_path(shipment), :confirm => 'Are you sure?' , :class => 'btn pull-right btn-danger'
    = link_to 'Edit', edit_users_shipment_path(shipment), :class => 'btn btn-info pull-right'
    - if s.invoice
      = link_to 'Invoice', edit_users_invoice_path(shipment.invoice), :class => 'btn btn-info pull-right'
    - else
      = link_to 'Invoice', new_users_invoice_path(:shipment => shipment), :class => 'btn btn-info pull-right'
    %span
      Shipment -
      = shipment.broker.name.titleize if shipment.broker
      = shipment.load_number
      = shipment.truck.name.titleize if shipment.truck
      = shipment.pick_up_date
  .mws-panel-body.no-padding
    %ul.mws-summary.clearfix
      %li
        %span.key
          = t(:load_conformation_pdf)
        %span.val
          %span.text-nowrap
            - unless shipment.load_conformation_pdf.blank?
              = link_to t(:load_conformation_pdf), shipment.load_conformation_pdf_url, :target => '_blanl'
            - else
              %span{:style => 'color:#F00'}= t(:load_conformation)
      %li
        %span.key
          = t(:bill_of_lading_pdf)
        %span.val
          %span.text-nowrap
            - unless shipment.bill_of_lading_pdf.blank?
              = link_to t(:bill_of_lading_pdf), shipment.bill_of_lading_pdf_url, :target => '_blanl'
            - else
              %span{:style => 'color:#F00'}= t(:bill_of_lading_pdf)
      %li
        %span.key
          = t(:broker)
        %span.val
          %span.text-nowrap
            = link_to shipment.broker.name, users_broker_path(shipment.broker) if shipment.broker
      %li
        %span.key
          = t(:truck)
        %span.val
          %span.text-nowrap
            = link_to shipment.truck.name, users_truck_path(shipment.truck) if shipment.truck
      %li
        %span.key
          = t(:trailer)
        %span.val
          %span.text-nowrap
            = link_to shipment.trailer.name, users_trailer_path(shipment.trailer) if shipment.trailer
      %li
        %span.key
          = t(:load_number)
        %span.val
          %span.text-nowrap= shipment.load_number
      %li
        %span.key
          = t(:price)
        %span.val
          %span.text-nowrap= number_to_currency(shipment.price)
      %li
        %span.key
          = t(:miles)
        %span.val
          %span.text-nowrap= shipment.miles
      %li
        %span.key
          = t(:pick_up_location_address)
        %span.val
          %span.text-nowrap
            - address = shipment.pick_up_location_address + ' ' + shipment.pick_up_location_address2 + ' ' + shipment.pick_up_location_city  + ' ' + shipment.pick_up_location_state  + ' ' + shipment.pick_up_location_zip
            = address
            = link_to 'https://maps.google.com/maps?q='+ address  +'&t=m&z=17', :target => '_blank' do
              %i.icol32-map2
      %li
        %span.key
          = t(:pick_up_location_phone)
        %span.val
          %span.text-nowrap= number_to_phone(shipment.pick_up_location_phone)
      %li
        %span.key
          = t(:delivery_location_address)
        %span.val
          %span.text-nowrap
            - address = shipment.delivery_location_address + ' ' + shipment.delivery_location_address2 + ' ' + shipment.delivery_location_city  + ' ' + shipment.delivery_location_state  + ' ' + shipment.delivery_location_zip
            = address
            = link_to 'https://maps.google.com/maps?q='+ address  +'&t=m&z=17', :target => '_blank' do
              %i.icol32-map2
      %li
        %span.key
          = t(:delivery_location_phone)
        %span.val
          %span.text-nowrap= number_to_phone(shipment.delivery_location_phone)
      %li
        %span.key
          = t(:number_of_stops)
        %span.val
          %span.text-nowrap= shipment.number_of_stops
      %li
        %span.key
          = t(:notes)
        %span.val
          %span.text-nowrap= raw shipment.notes.gsub("\r\n" ,'<br>')
      %li
        %span.key
          = t(:pick_up_date)
        %span.val
          %span.text-nowrap= shipment.pick_up_date
      %li
        %span.key
          = t(:deliver_date)
        %span.val
          %span.text-nowrap= shipment.deliver_date
      %li
        %span.key
          = t(:status)
        %span.val
          %span.text-nowrap= shipment.status
      %li
        %span.key
          = t(:weight)
        %span.val
          %span.text-nowrap= shipment.weight
      %li
        %span.key
          = t(:drivers_notes)
        %span.val
          %span.text-nowrap= raw shipment.drivers_notes.gsub("\r\n" ,'<br>')
      %li
        %span.key
          = t(:packing)
        %span.val
          %span.text-nowrap= shipment.packing
      %li
        %span.key
          = t(:seal_number)
        %span.val
          %span.text-nowrap= shipment.seal_number
      %li
        %span.key
          = t(:license)
        %span.val
          %span.text-nowrap
            - if shipment.double_triple_trailers
              = t(:double_triple_trailers)
            - if shipment.passenger
              = t(:passenger)
            - if shipment.tank_vehicle
              = t(:tank_vehicle)
            - if shipment.hazardous_materials
              = t(:hazardous_materials)
            - if shipment.twic_card
              = t(:twic_card)
      %li
        %span.key
          = t(:suspension)
        %span.val
          %span.text-nowrap= shipment.suspension
      -#%li
        %span.key
          = t(:paid_status)
        %span.val
          %span.text-nowrap= shipment.paid_status
      -#%li
        %span.key
          = t(:paid_date)
        %span.val
          %span.text-nowrap= shipment.paid_date
      %li
        %span.key
          = t(:load_conformation)
        %span.val
          %span.text-nowrap= shipment.load_conformation
      %li
        %span.key
          = t(:equipment_type)
        %span.val
          %span.text-nowrap= shipment.equipment_type
      %li
        %span.key
          = t(:size_of_trailer)
        %span.val
          %span.text-nowrap= shipment.size_of_trailer
      %li
        %span.key
          = t(:number_of_pallets)
        %span.val
          %span.text-nowrap= shipment.pallets_pisses
      %li
        %span.key
          = t(:pick_up_number)
        %span.val
          %span.text-nowrap= shipment.pick_up_number
      %li
        %span.key
          = t(:delivery_number)
        %span.val
          %span.text-nowrap= shipment.delivery_number
      %li
        %span.key
          = t(:pick_up_earlier_time)
        %span.val
          %span.text-nowrap= shipment.pick_up_earlier_time
      %li
        %span.key
          = t(:pick_up_latest_time)
        %span.val
          %span.text-nowrap= shipment.pick_up_lateest_time
      %li
        %span.key
          = t(:pick_up_appointment)
        %span.val
          %span.text-nowrap= shipment.pick_up_appointment
      %li
        %span.key
          = t(:delivery_earlier_time)
        %span.val
          %span.text-nowrap= shipment.delivery_earlier_time
      %li
        %span.key
          = t(:delivery_latest_time)
        %span.val
          %span.text-nowrap= shipment.delivery_lateest_time
      %li
        %span.key
          = t(:trailer_type)
        %span.val
          %span.text-nowrap= shipment.trailer_type
      %li
        %span.key
          = t(:delivery_appointment)
        %span.val
          %span.text-nowrap= shipment.delivery_appointment

%a{:name => "notes"}
.mws-panel.grid_12
  .mws-panel-header
    %span
      Notes
  .mws-panel-body.no-padding
    %ul.mws-summary.clearfix
      - Comment.where(:commenter_type => 'shipment').where(:commenter_id => shipment.id).order('id DESC').each do |c|
        %li
          %span.key
            - if c.user.photo_url
              = image_tag c.user.photo.thumb, :alt => c.user.full_name, :width => 25
            - else
              = image_tag '/assets/example/profile.jpg', :alt => c.user.full_name, :width => 25
            = c.user.name.titleize
          %span.val
            %span.text-nowrap
              =raw c.note

              .pull-right= c.created_at.in_time_zone('Eastern Time (US & Canada)').strftime('%D %r')
        .clear
.clear
.row-fluid
.mws-panel.grid_12
  .mws-panel-header
    %span Add Notes
  .mws-panel-body
    = form_for comment, :url => comments_path(:commenter_type => "shipment", :commenter_id => shipment.id) do |f|
      .mws-form-row
        %label.mws-form-label
          Note
        .mws-form-item
          = f.text_area :note, :class => 'cleditor'
        %br
        = f.button :submit, :class => 'btn btn-info'