config/routes.rb
Gotrucker::Application.routes.draw do
  devise_for :users, :controllers => { registrations:  'users/registrations',
                                      :sessions => "users/sessions",
                                      :passwords => 'users/passwords',
                                      :confirmations => 'users/confirmations'
  }
  authenticate :user do
    namespace :users do
      resources :ui
      resources :users
      resources :accounts, :only => [:show, :edit, :update]
      resources :drivers
      resources :profile, :only => [:edit, :update]
      resources :trucks
      resources :trailers
      resources :brokers do
        collection { post :import }
      end
      match "/shipments/delete" => "shipments#delete", :as => :shipments_delete
      resources :shipments
      resources :receipts
      resources :repairs
      match '/invoices/:id/pdf' => 'invoices#pdf', :as => :invoices_pdf
      resources :invoices
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
    end
  end

   devise_for :admins, :controllers => { registrations: 'admins/registrations',
                                       :sessions => "admins/sessions",
                                       :passwords => 'admins/passwords',
                                       :confirmations => 'admins/confirmations'
   }
   authenticate :admin do
     namespace :admins do
       resources :ui
       resources :accounts
       resources :admins
       resources :brokers
       resources :drivers
       resources :leads
       resources :plans
       resources :profile, :only => [:edit, :update]
       resources :receipts
       resources :repairs
       resources :shipments
       resources :trailers
       resources :trucks
       resources :users
       post '/users/login_as' => 'users#login_as', as: :login_as_user
       get '/dashboard' => 'dashboards#index', as: :dashboard
       get '/' => 'dashboards#index'
     end
   end

#   namespace :api do
#     namespace :internal do
#       namespace :v1 do
#         resources :users
#         resources :drivers
#         resources :trucks
#         resources :trailers
#         resources :brokers
#         resources :shipments
#         resources :receipts
#         resources :repairs
#         resources :invoices
#       end
#     end
#   end
  resources :comments
  resources :leads, :only => [:new, :create]
  post '/sign_up' => 'pages#sign_up', :as => :sign_up
  match '/contact_us' => 'leads#new', :as => :contact_us
  match '/thanks' => 'leads#thanks', :as => :thanks
  match "/prices" => "pages#prices", :as => :prices
  match "/about_us" => "pages#about_us", :as => :about_us
  match "/test" => "pages#test", :as => :test
  root :to => 'pages#index'
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :truck
  belongs_to :trailer
  belongs_to :account
  has_many :comments, :as => :commenter

  attr_accessible :truck_id, :trailer_id, :service_provider_name, :service_provider_address, :service_provider_address2, :service_provider_city, :service_provider_state, :service_provider_zip, :service_provider_fax, :service_provider_phone, :delivery_date, :return_date, :payment_info, :invoice_date, :invoice_number, :details, :labor, :parts, :tax, :total, :account_id, :invoice
  

  before_validation { |repair| repair.service_provider_phone = service_provider_phone.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |repair| repair.service_provider_fax = service_provider_fax.to_s.gsub(/[^0-9]/, "").to_s }
  before_validation { |repair| repair.service_provider_zip = service_provider_zip.to_s.gsub(/[^0-9]/, "").to_s }
  before_save { |repair| repair.total = repair.labor.to_i + repair.parts.to_i + repair.tax.to_i }
  
  mount_uploader :invoice, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  has_many :comments
  has_many :comments, :as => :commenter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :photo, :phone, :active, :is_owner, :is_primary, :account_id, :plan_slug, :s, :account_attributes, :subscriptions_type

  validates_uniqueness_of :email
  validates_presence_of :password, :if => :should_validate_password?

  attr_accessor :updating_password
  attr_accessor :plan_slug
  attr_accessor :s
  attr_accessor :subscriptions_type
  accepts_nested_attributes_for :account
  mount_uploader :photo, PhotoUploader

  def name
    full_name
  end

  def full_name
    first_name + ' ' + last_name
  end
  def should_validate_password?
      updating_password || new_record?
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminController
  before_filter :check_password_submitted, :only => :update
  expose(:users) {User.order("id DESC").scoped{}}
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(admins_user_path(user))
    else
      render :new
    end
  end

  def update
    if user.update_attributes(params[:user])
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(admins_user_path(user))
    else
      render :edit
    end
  end
  def login_as
    sign_in(User.find(params[:id]), :bypass => true)
    redirect_to users_dashboard_path
  end
  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/api/internal/v1/users_controller.rb
class Api::Internal::V1::UsersController < ApiController
  expose(:users){ User.all }
  expose(:user){ User.find(params[:id]) }
  respond_to :json
  before_filter :check_api_key


  private
  def check_api_key
    unless params['api_key'] == ENV['INTERNAL_API_KEY']
      respond_with({:result => 'Invalid API Key'})
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  expose(:current_account){ current_user.account }
  layout 'user_application'
  before_filter :check_user_active
  before_filter :check_unpaid_invoices
  private
    def check_user_active
      unless current_user.active
        flash[:notice]= t(:user_not_active)
        sign_out current_user
        redirect_to new_user_session_path
      end
    end
    def check_unpaid_invoices
      if current_account.invoices.count > 0
        if current_account.invoices.where(:paid_status => 'unpaid').where("created_at <= ?", Time.now - 30.days).count > 0
          flash[:error]= 'There are unpaid invoices over 30 days'
        end
      end
  end
end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < UserController
  before_filter :check_user_level
  expose(:account) {current_account}

  def create
    if account.save
      flash[:notice] = t(:account_was_successfully_created)
      redirect_to(users_account_path(current_account))
    else
      render :new
    end
  end

  def update
    if account.update_attributes(params[:account])
      flash[:notice] = t(:account_was_successfully_updated)
      redirect_to(users_account_path(current_account))
    else
      render :edit
    end
  end
  private
  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/controllers/users/brokers_controller.rb
class Users::BrokersController < UserController
  require 'csv'
  expose(:brokers){ current_account.brokers.order("id DESC").scoped{} }
  expose(:broker)
  expose(:comment) { broker.comments.new}

  def create
    if broker.save
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
    else
      render :new
    end
  end

  def update
    if broker.save
      flash[:notice] = t(:broker_was_successfully_updated)
      redirect_to(users_brokers_path)
    else
      render :edit
    end
  end


  def import
    puts params
    csv_text = File.read('public/brokers.csv')
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
        current_account.brokers.create!(row.to_hash)
    end
      flash[:notice] = t(:broker_was_successfully_created)
      redirect_to(users_brokers_path)
  end 
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:drivers){ current_account.drivers.where(:active => true).order("id DESC").scoped{} }
end

app/controllers/users/drivers_controller.rb
class Users::DriversController < UserController
  expose(:drivers){ current_account.drivers.order("id DESC").scoped{} }
  expose(:driver)
  expose(:comment) { driver.comments.new}

  def create
    if driver.save
      flash[:notice] = t(:driver_was_successfully_created)
      redirect_to(users_drivers_path)
    else
      render :new
    end
  end

  def update
    if driver.save
      flash[:notice] = t(:driver_was_successfully_updated)
      redirect_to(users_drivers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/invoices_controller.rb
class Users::InvoicesController < UserController
  expose(:invoices){ current_account.invoices.order("id DESC").scoped{} }
  expose(:invoice)
  expose(:comment) { invoice.comments.new}
  expose(:shipment) {
    if params[:shipment]
      current_account.shipments.find(params[:shipment])
    else
      false
    end
  }

  def create
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_created)
      redirect_to(users_invoices_path)
    else
      render :new
    end
  end

  def update
    if invoice.save
      flash[:notice] = t(:invoice_was_successfully_updated)
      redirect_to(users_invoices_path)
    else
      render :edit
    end
  end
  
  def pdf
    render :layout => 'invoice'
    #render :layout => false  
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'user_login'
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < UserController
  before_filter :check_password_submitted, :only => :update
  expose(:user){ current_user }
  def update
    if user.update_attributes(params[:user])
      sign_in(current_user, :bypass => true)
      flash[:notice] = t(:profile_was_successfully_updated)
      redirect_to users_dashboard_path
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end
end

app/controllers/users/receipts_controller.rb
class Users::ReceiptsController < UserController
  expose(:receipts){ current_account.receipts.order("id DESC").scoped{} }
  expose(:receipt)
  expose(:comment) { receipt.comments.new}

  def create
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_created)
      redirect_to(users_receipts_path)
    else
      render :new
    end
  end

  def update
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_updated)
      redirect_to(users_receipts_path)
    else
      render :edit
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 #layout 'application'
 before_filter :before_create_account, :only => [:create]
 after_filter :account_must_have_a_plan, :only => [:create]
 expose(:plan){Plan.find_by_slug(params[:plan])}
 def new
  redirect_to user_dashboard_path if current_user
  resource = build_resource({})
  resource.build_account
  resource.account.build_subscription
  resource.plan_slug = plan.slug if plan
  respond_with resource
 end

 def after_inactive_sign_up_path_for(resource)
   users_dashboard_path
 end

 def after_sign_up_path_for(resource)
   sign_in(resource)
   users_dashboard_path
 end

 private
 def before_create_account
    params[:user][:is_owner] = true
    params[:user][:is_primary] = true
 end

 def account_must_have_a_plan
   unless resource.new_record?
     s = Subscription.find_by_key(params[:user][:s])
     plan = Plan.find_by_slug(s.item_number)

     params[:user][:subscriptions_type] = 'monthly'
     if params[:user][:subscriptions_type] == 'monthly'
       price = plan.monthy_price
     else
       price = plan.yearly_price
     end
     s.update_attributes(:account_id => resource.account.id, :plan_id => plan.id, :name => plan.name, :price => price, :slug => plan.slug, :licenses => plan.licenses, :subscriptions_type => params[:user][:subscriptions_type]  )
   end
 end

end

app/controllers/users/repairs_controller.rb
class Users::RepairsController < UserController
  expose(:repairs){ current_account.repairs.order("id DESC").scoped{} }
  expose(:repair)
  expose(:comment) { repair.comments.new}

  def create
    if repair.save
      flash[:notice] = t(:repair_was_successfully_created)
      redirect_to(users_repairs_path)
    else
      render :new
    end
  end

  def update
    if repair.save
      flash[:notice] = t(:repair_was_successfully_updated)
      redirect_to(users_repairs_path)
    else
      render :edit
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'user_login'
  private
  def after_sign_in_path_for(resource)
    users_dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/users/shipments_controller.rb
class Users::ShipmentsController < UserController
  expose(:shipments){ current_account.shipments.order("id DESC").scoped{} }
  expose(:shipment)
  expose(:comment) { shipment.comments.new}

  def create
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_created)
      redirect_to(users_shipments_path)
    else
      render :new
    end
  end

  def update
    if shipment.save
      flash[:notice] = t(:shipment_was_successfully_updated)
      redirect_to(users_shipments_path)
    else
      render :edit
    end
  end
   def delete
     s = Shipment.find(params[:format])
     s.delete
      flash[:notice] = t(:shipment_was_successfully_deleted)
      redirect_to(users_shipments_path)
   end
end

app/controllers/users/trailers_controller.rb
class Users::TrailersController < UserController
  expose(:trailers){ current_account.trailers.order("id DESC").scoped{} }
  expose(:trailer)
  expose(:comment) { trailer.comments.new}

  def create
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_created)
      redirect_to(users_trailers_path)
    else
      render :new
    end
  end

  def update
    if trailer.save
      flash[:notice] = t(:trailer_was_successfully_updated)
      redirect_to(users_trailers_path)
    else
      render :edit
    end
  end
end

app/controllers/users/trucks_controller.rb
class Users::TrucksController < UserController
  expose(:trucks){ current_account.trucks.order("id DESC").scoped{} }
  expose(:truck)
  expose(:comment) { truck.comments.new}

  def create
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_created)
      redirect_to(users_trucks_path)
    else
      render :new
    end
  end

  def update
    if current_account.subscription.licenses <= current_account.trucks.where(:active => true).count
      truck.active = false
      flash[:error] = t(:excited_licenses)
    end
    if truck.save
      flash[:notice] = t(:truck_was_successfully_updated)
      redirect_to(users_trucks_path)
    else
      render :edit
    end
  end
  private
  def check_licences
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < UserController
  before_filter :check_password_submitted, :only => :update
  before_filter :check_user_level
  expose(:users){ current_account.users.order("id DESC").scoped{} }
  expose(:user)
  expose(:comment) { user.comments.new}

  def create
    if user.save
      flash[:notice] = t(:user_was_successfully_created)
      redirect_to(users_users_path)
    else
      render :new
    end
  end

  def update
    if user.save
      flash[:notice] = t(:user_was_successfully_updated)
      redirect_to(users_users_path)
    else
      render :edit
    end
  end

  private
  def check_password_submitted
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      user.updating_password = false
    else
      user.updating_password = true
    end
  end

  def check_user_level
    unless current_user.is_owner?
      flash[:error] = t(:access_denied)
      redirect_to(users_dashboard_path)
    end
  end
end

app/views/users/repairs/_form.html.haml
= simple_form_for([:users, repair], :html => {:class => 'form-horizontal' }) do |f|
  .mws-form-row
    %label.mws-form-label= t(:truck)
    .mws-form-item
    = f.association :truck, collection: current_account.trucks.all(order: 'name'), prompt: "Choose a Truck", :label => false
  .mws-form-row
    %label.mws-form-label= t(:trailer)
    .mws-form-item
    = f.association :trailer, collection: current_account.trailers.all(order: 'name'), prompt: "Choose a Trailer", :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_name)
    .mws-form-item
    = f.input :service_provider_name, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_address)
    .mws-form-item
    = f.input :service_provider_address, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_address2)
    .mws-form-item
    = f.input :service_provider_address2, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_city)
    .mws-form-item
    = f.input :service_provider_city, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_state)
    .mws-form-item
    = f.input :service_provider_state, :collection => us_states,  :as => :select, include_blank: true, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_zip)
    .mws-form-item
    = f.input :service_provider_zip, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_fax)
    .mws-form-item
    = f.input :service_provider_fax, :label => false
  .mws-form-row
    %label.mws-form-label= t(:service_provider_phone)
    .mws-form-item
    = f.input :service_provider_phone, :label => false
  .mws-form-row
    %label.mws-form-label= t(:delivery_date)
    .mws-form-item
    = f.input :delivery_date, :label => false, :input_html => { :class => 'datepicker'}
  .mws-form-row
    %label.mws-form-label= t(:return_date)
    .mws-form-item
    = f.input :return_date, :label => false, :input_html => { :class => 'datepicker'}
  .mws-form-row
    %label.mws-form-label= t(:payment_info)
    .mws-form-item
    = f.input :payment_info, :collection => payment_method_list,  :as => :select, include_blank: false, :label => false
  .mws-form-row
    %label.mws-form-label= t(:invoice_date)
    .mws-form-item
    = f.input :invoice_date, :label => false, :input_html => { :class => 'datepicker'}
  .mws-form-row
    %label.mws-form-label= t(:invoice_number)
    .mws-form-item
    = f.input :invoice_number, :label => false
  .mws-form-row
    %label.mws-form-label= t(:details)
    .mws-form-item
    = f.input :details, :label => false
  .mws-form-row
    %label.mws-form-label= t(:labor)
    .mws-form-item
    = f.input :labor, :label => false
  .mws-form-row
    %label.mws-form-label= t(:parts)
    .mws-form-item
    = f.input :parts, :label => false
  .mws-form-row
    %label.mws-form-label= t(:tax)
    .mws-form-item
    = f.input :tax, :label => false
  .mws-form-row
    %label.mws-form-label= t(:invoice)
    .mws-form-item
    = f.input :invoice, :label => false

  .mws-form-row
    .mws-form-item
    = f.button :submit, :class => 'pull-right btn btn-info'

app/views/users/repairs/edit.html.haml
- content_for :pagetitle do 
  Edit Repairs
%h1#main-heading
  Update Repair

=render 'form'

app/views/users/repairs/index.html.haml
- content_for :pagetitle do 
  Repairs
.grid_8
  = link_to t(:add_repair), new_users_repair_path, :class => 'btn btn-info pull-right'
.mws-panel.grid_8
  .mws-panel-header
    %span
      Repairs
  .mws-panel-body.no-padding
    %table.mws-datatable-fn.mws-table
      %thead
        %tr
          %th
          %th= t(:service_provider_name)
          %th= t(:truck)
          %th= t(:trailer)
          %th= t(:city)
          %th= t(:state)
          %th= t(:phone)
          %th= t(:invoice_date)
          %th= t(:delivery_date)
          %th= t(:return_date)
          %th= t(:total)
          %th
      %tbody
        - repairs.each do |r|
          %tr
            %td= link_to t(:show), users_repair_path(r), :class => 'btn btn-small btn-info'
            %td= link_to r.service_provider_name, users_repair_path(r)
            %td= link_to r.truck.name, users_truck_path(r.truck) if r.truck
            %td= link_to r.trailer.name, users_trailer_path(r.trailer) if  r.trailer
            %td= r.service_provider_city
            %td= r.service_provider_state
            %td= number_to_phone(r.service_provider_phone)
            %td= r.invoice_date
            %td= r.delivery_date
            %td= r.return_date
            %td= number_to_currency(r.total)
            %td= link_to 'Edit', edit_users_repair_path(r), :class => 'btn btn-small btn-info'

app/views/users/repairs/new.html.haml
- content_for :pagetitle do 
  Edit Repairs
%h1#main-heading
  Create Repair

=render 'form'

app/views/users/repairs/show.html.haml
- content_for :pagetitle do 
  Show Repairs
.mws-panel.grid_12
  .mws-panel-header
    = link_to 'Edit', edit_users_repair_path(repair), :class => 'btn btn-info pull-right'
    %span
      Repair - 
      = repair.service_provider_name.titleize
      |
      = repair.truck.name.titleize if repair.truck
      |
      = repair.trailer.name.titleize if repair.trailer
      |
      = repair.invoice_number
  .mws-panel-body.no-padding
    %ul.mws-summary.clearfix
      %li
        %span.key
          = t(:truck)
        %span.val
          %span.text-nowrap= repair.truck.name.titleize if repair.truck
      %li
        %span.key
          = t(:trailer)
        %span.val
          %span.text-nowrap= repair.trailer.name.titleize if repair.trailer
      %li
        %span.key
          = t(:service_provider_name)
        %span.val
          %span.text-nowrap= repair.service_provider_name.titleize
      %li
        %span.key
          = t(:invoice)
        %span.val
          %span.text-nowrap
            - unless repair.invoice.blank?
              = link_to t(:invoice), repair.invoice_url, :target => '_blanl'
            - else
              %span{:style => 'color:#F00'}= t(:invoice)
      %li
        %span.key
          = t(:address)
        %span.val
          %span.text-nowrap
            - address = repair.service_provider_address + ' ' + repair.service_provider_address2 + ' ' + repair.service_provider_city  + ' ' + repair.service_provider_state  + ' ' + repair.service_provider_zip
            = address
            = link_to 'https://maps.google.com/maps?q='+ address  +'&t=m&z=17', :target => '_blank' do
              %i.icol32-map2
      %li
        %span.key
          = t(:service_provider_phone)
        %span.val
          %span.text-nowrap= number_to_phone(repair.service_provider_phone)
      %li
        %span.key
          = t(:service_provider_fax)
        %span.val
          %span.text-nowrap= number_to_phone(repair.service_provider_fax)
      %li
        %span.key
          = t(:delivery_date)
        %span.val
          %span.text-nowrap= repair.delivery_date
      %li
        %span.key
          = t(:return_date)
        %span.val
          %span.text-nowrap= repair.return_date
      %li
        %span.key
          = t(:payment_info)
        %span.val
          %span.text-nowrap= repair.payment_info
      %li
        %span.key
          = t(:invoice_date)
        %span.val
          %span.text-nowrap= repair.invoice_date
      %li
        %span.key
          = t(:invoice_number)
        %span.val
          %span.text-nowrap= repair.invoice_number
      %li
        %span.key
          = t(:details)
        %span.val
          %span.text-nowrap= repair.details
      %li
        %span.key
          = t(:labor)
        %span.val
          %span.text-nowrap= number_to_currency(repair.labor)
      %li
        %span.key
          = t(:parts)
        %span.val
          %span.text-nowrap= number_to_currency(repair.parts)
      %li
        %span.key
          = t(:tax)
        %span.val
          %span.text-nowrap= number_to_currency(repair.tax)
      %li
        %span.key
          = t(:total)
        %span.val
          %span.text-nowrap= number_to_currency(repair.total)
.clear
  
%a{:name => "notes"}
.mws-panel.grid_12
  .mws-panel-header
    %span
      Notes
  .mws-panel-body.no-padding
    %ul.mws-summary.clearfix
      - Comment.where(:commenter_type => 'repair').where(:commenter_id => repair.id).order('id DESC').each do |c|
        %li
          %span.key
            - if c.user.photo_url
              = image_tag c.user.photo.thumb, :alt => c.user.full_name, :width => 25
            - else
              = image_tag '/assets/example/profile.jpg', :alt => c.user.full_name, :width => 25
            = c.user.name.titleize
          %span.val
            %span.text-nowrap
              =raw c.note

              .pull-right= c.created_at.in_time_zone('Eastern Time (US & Canada)').strftime('%D %r')
        .clear
.clear
.row-fluid
.mws-panel.grid_12
  .mws-panel-header
    %span Add Notes
  .mws-panel-body
    = form_for comment, :url => comments_path(:commenter_type => "repair", :commenter_id => repair.id) do |f|
      .mws-form-row
        %label.mws-form-label
          Note
        .mws-form-item
          = f.text_area :note, :class => 'cleditor'
        %br
        = f.button :submit, :class => 'btn btn-info'